var tokenList = {},

    testTokens = function () {

        tokenList.empty_tokens = [
            {lexeme: 'EOF', kind: 'EOF'}
        ]

        tokenList.sample1_tokens = [
            {lexeme: 'x', kind: 'id', line: 1, col: 1},
            {lexeme: 'is', kind: 'is', line: 1, col: 3},
            {lexeme: '3', kind: 'intlit', line: 1, col: 6},
            {lexeme: '*', kind: '*', line: 1, col: 8},
            {lexeme: '4', kind: 'intlit', line: 1, col: 10},
            {lexeme: '/', kind: '/', line: 1, col: 12},
            {lexeme: '2', kind: 'intlit', line: 1, col: 14},
            {lexeme: 'newline', kind: 'newline', line: 1, col: 15},
            {lexeme: 'y', kind: 'is', line: 2, col: 1},
            {lexeme: 'is', kind: 'is', line: 2, col: 3},
            {lexeme: 'yah', kind: 'yah', line: 2, col: 6},
            {lexeme: 'newline', kind: 'newline', line: 2, col: 9},
            {lexeme: 'trix', kind: 'id', line: 4, col: 1},
            {lexeme: 'is', kind: 'is', line: 4, col: 6},
            {lexeme: '4kdz', kind: 'strlit', line: 4, col: 9},
            {lexeme: 'newline', kind: 'newline', line: 4, col: 21},
            {lexeme: 'addOne', kind: 'id', line: 6, col: 1},
            {lexeme: 'is', kind: 'is', line: 6, col: 8},
            {lexeme: '(', kind: '(', line: 6, col: 11},
            {lexeme: 'p', kind: 'id', line: 6, col: 12},
            {lexeme: ')', kind: ')', line: 6, col: 13},
            {lexeme: '->', kind: '->', line: 6, col: 15},
            {lexeme: 'newline', kind: 'newline', line: 6, col: 17},
            {lexeme: 'spit', kind: 'spit', line: 7, col: 3},
            {lexeme: 'p', kind: 'id', line: 7, col: 8},
            {lexeme: '+', kind: '+', line: 7, col: 10},
            {lexeme: '1', kind: 'intlit', line: 7, col: 12},
            {lexeme: 'newline', kind: 'newline', line: 7, col: 13},
            {lexeme: 'a', kind: 'id', line: 9, col: 1},
            {lexeme: 'is', kind: 'is', line: 9, col: 3},
            {lexeme: 'nil', kind: 'nil', line: 9, col: 6},
            {lexeme: 'newline', kind: 'newline', line: 9, col: 9},
            {lexeme: 'b', kind: 'id', line: 10, col: 1},
            {lexeme: 'is', kind: 'is', line: 10, col: 3},
            {lexeme: 'undefined', kind: 'undefined', line: 10, col: 6},
            {lexeme: 'newline', kind: 'newline', line: 10, col: 15},
            {lexeme: 'c', kind: 'NaN', line: 11, col: 1},
            {lexeme: 'is', kind: 'is', line: 11, col: 3},
            {lexeme: 'NaN', kind: 'NaN', line: 11, col: 6},
            {lexeme: 'newline', kind: 'newline', line: 11, col: 9},
            {lexeme: 'l', kind: 'id', line: 13, col: 1},
            {lexeme: 'is', kind: 'is', line: 13, col: 3},
            {lexeme: '[', kind: '[', line: 13, col: 6},
            {lexeme: '1', kind: 'intlit', line: 13, col: 7},
            {lexeme: ',', kind: ',', line: 13, col: 8},
            {lexeme: '2', kind: 'intlit', line: 13, col: 9},
            {lexeme: ',', kind: ',', line: 13, col: 10},
            {lexeme: 'x', kind: 'id', line: 13, col: 11},
            {lexeme: ']', kind: ']', line: 13, col: 12},
            {lexeme: 'newline', kind: 'newline', line: 13, col: 13},
            {lexeme: 't', kind: 'id', line: 14, col: 1},
            {lexeme: 'is', kind: 'is', line: 14, col: 3},
            {lexeme: '(', kind: '(', line: 14, col: 6},
            {lexeme: 'a', kind: 'id', line: 14, col: 7},
            {lexeme: ',', kind: ',', line: 14, col: 8},
            {lexeme: 'y', kind: 'id', line: 14, col: 9},
            {lexeme: ',', kind: ',', line: 14, col: 10},
            {lexeme: 'trix', kind: 'id', line: 14, col: 11},
            {lexeme: ')', kind: ')', line: 14, col: 15},
            {lexeme: 'newline', kind: 'newline', line: 14, col: 16},
            {lexeme: 'sample', kind: 'id', line: 16, col: 1},
            {lexeme: '(', kind: '(', line: 16, col: 7},
            {lexeme: '(', kind: '(', line: 16, col: 8},
            {lexeme: 'x', kind: 'id', line: 16, col: 9},
            {lexeme: ')', kind: ')', line: 16, col: 10},
            {lexeme: '->', kind: '->', line: 16, col: 12},
            {lexeme: 'print', kind: 'print', line: 16, col: 15},
            {lexeme: '(', kind: '(', line: 16, col: 16},
            {lexeme: 'x', kind: 'id', line: 16, col: 17},
            {lexeme: ')', kind: ')', line: 16, col: 18},
            {lexeme: ')', kind: ')', line: 16, col: 19},
            {lexeme: 'newline', kind: 'newline', line: 14, col: 20},
            {lexeme: 'EOF', kind: 'EOF'}
        ]

        return tokenList;
    }();

module.exports = testTokens;